name: Compile LaTeX File into PDF

on:
  push:
    branches:
      - main

jobs:
  latex-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LaTeX (TeX Live)
        run: sudo apt-get install -y texlive

      - name: Compile LaTeX file into PDF
        run: |
          pdflatex myfile.tex
