name: Package Files into Tarball

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a tarball package
        run: |
          tar -czvf project.tar.gz *
